# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\x1a\x1cgoogle/api/annotations.proto\"0\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06trx_id\x18\x03 \x01(\t\"\'\n\x07NewUser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06trx_id\x18\x02 \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"5\n\x11\x43reateUserRequest\x12 \n\x08new_user\x18\x01 \x01(\x0b\x32\x0e.users.NewUser\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf6\x02\n\x17UserGRPCAndRESTServices\x12K\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x0e\x82\xd3\xe4\x93\x02\x08\x12\x06/users\x12Y\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\x0b/users/{id}\x12[\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\x06/users:\x08new_user\x12V\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\"\x13\x82\xd3\xe4\x93\x02\r*\x0b/users/{id}b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['GetUsers']._loaded_options = None
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['GetUsers']._serialized_options = b'\202\323\344\223\002\010\022\006/users'
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['GetUserById']._loaded_options = None
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['GetUserById']._serialized_options = b'\202\323\344\223\002\r\022\013/users/{id}'
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['CreateUser']._loaded_options = None
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['CreateUser']._serialized_options = b'\202\323\344\223\002\022\"\006/users:\010new_user'
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['DeleteUser']._loaded_options = None
  _globals['_USERGRPCANDRESTSERVICES'].methods_by_name['DeleteUser']._serialized_options = b'\202\323\344\223\002\r*\013/users/{id}'
  _globals['_USER']._serialized_start=52
  _globals['_USER']._serialized_end=100
  _globals['_NEWUSER']._serialized_start=102
  _globals['_NEWUSER']._serialized_end=141
  _globals['_GETUSERSREQUEST']._serialized_start=143
  _globals['_GETUSERSREQUEST']._serialized_end=160
  _globals['_GETUSERSRESPONSE']._serialized_start=162
  _globals['_GETUSERSRESPONSE']._serialized_end=208
  _globals['_GETUSERBYIDREQUEST']._serialized_start=210
  _globals['_GETUSERBYIDREQUEST']._serialized_end=242
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=244
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=292
  _globals['_CREATEUSERREQUEST']._serialized_start=294
  _globals['_CREATEUSERREQUEST']._serialized_end=347
  _globals['_CREATEUSERRESPONSE']._serialized_start=349
  _globals['_CREATEUSERRESPONSE']._serialized_end=386
  _globals['_DELETEUSERREQUEST']._serialized_start=388
  _globals['_DELETEUSERREQUEST']._serialized_end=419
  _globals['_DELETEUSERRESPONSE']._serialized_start=421
  _globals['_DELETEUSERRESPONSE']._serialized_end=458
  _globals['_USERGRPCANDRESTSERVICES']._serialized_start=461
  _globals['_USERGRPCANDRESTSERVICES']._serialized_end=835
# @@protoc_insertion_point(module_scope)
