# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"2\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11\x44\x65leteUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x44\x65leteUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\xca\x01\n\x05Users\x12;\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\x12\x41\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12\x41\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=72
  _globals['_GETUSERSREQUEST']._serialized_start=74
  _globals['_GETUSERSREQUEST']._serialized_end=91
  _globals['_GETUSERSRESPONSE']._serialized_start=93
  _globals['_GETUSERSRESPONSE']._serialized_end=139
  _globals['_CREATEUSERREQUEST']._serialized_start=141
  _globals['_CREATEUSERREQUEST']._serialized_end=187
  _globals['_CREATEUSERRESPONSE']._serialized_start=189
  _globals['_CREATEUSERRESPONSE']._serialized_end=236
  _globals['_DELETEUSERREQUEST']._serialized_start=238
  _globals['_DELETEUSERREQUEST']._serialized_end=284
  _globals['_DELETEUSERRESPONSE']._serialized_start=286
  _globals['_DELETEUSERRESPONSE']._serialized_end=333
  _globals['_USERS']._serialized_start=336
  _globals['_USERS']._serialized_end=538
# @@protoc_insertion_point(module_scope)
